templates/deployment.yaml

fix: volume declaration mixed with toleration

---

README.md
values.yaml

- Update minimal kubernetes requirements
- Add two values.yaml examples
- Add links to ollama documentation (RESTful API, Clients libraries)
- Update keys's comments in values.yaml

docs: update documentation

---

Chart.yaml
README.md
templates/deployment.yaml
values.yaml

- Add `ollama.gpu.type` key default to 'nvidia'
- Add AMD support
- Add `extraEnv` key

Feat: Add AMD GPU suppport

---

Chart.yaml

- upgrade ollama app version to 0.1.30 in Chart.yaml

feat: upgrade appVersion to 0.1.30

---

Chart.yaml

Feats:
- upgrade app version to 0.1.31

feat: upgrade app version to 0.1.31

---

Chart.yaml
README.md

Changes:
- upgrade ollama to 0.1.32
- update README.md

Feat: Upgrade app version to 0.1.32

---

Chart.yaml

Changes:
- upgrade app version to 0.1.33

feat: upgrade app version to 0.1.33

---

Chart.yaml

Changes
- upgrade appVersion to 0.1.34

feat: upgrade appVersion to 0.1.34

---

Chart.yaml

Changes
- upgrade appVersion to 0.1.35

feat: upgrade appVersion to 0.1.35

---

Chart.yaml

Changes:
- upgrade appVersion to 0.1.36

feat: upgrade appVersion to 0.1.36

---

Chart.yaml

Changes:
- upgrade appVersion to 0.1.37

feat: upgrade appVersion to 0.1.37

---

Chart.yaml

Changes:
- upgrade appVersion to 0.1.38

feat: upgrade appVersion to 0.1.38

---

README.md
templates/service.yaml
values.yaml

Adds annoations to the service and values

feat: Add annotations to service

---

Chart.yaml

Changes:
- upgrade appVersion to 0.1.39

feat: upgrade appVersion to 0.1.39

---

Chart.yaml
README.md

Changes:
- upgrade app version to 0.1.40

feat: upgrade app version to 0.1.40

---

Chart.yaml

Changes:
- upgrade appVersion to 0.1.41

feat: upgrade app version to 0.1.41

---

Chart.yaml

Changes:
- upgrade ollama to appVersion 0.1.42

feat: upgrade app version to 0.1.42

---

Chart.yaml

Changes:
- upgrade appVersion to 0.1.43

feat: upgrade app version to 0.1.43

---

Chart.yaml

Changes:
- upgrade appVersion to 0.1.44

feat: upgrade app version to 0.1.44

---

Chart.yaml

Changes:
- update artifacthub annotations changes

feat: update artifacthub changes

---

Chart.yaml

Changes:
- upgrade appVersion to 0.1.45

feat: upgrade app version to 0.1.45

---

Chart.yaml
README.md

Changes:
- upgrade appVersion to 0.1.46

Upgrade app version to 0 1 46

---

Chart.yaml

Changes:
- upgrade appVersion to 0.1.47

feat: upgrade app version to 0.1.47

---

Chart.yaml

Changes:
- upgrade app version to 0.1.48

feat: upgrade app version to 0.1.48

---

Chart.yaml
README.md

Changes:
- upgrade app version to 0.2.0
- update README.md

feat: upgrade app version to 0.2.0

---

Chart.yaml

Changes:
- upgrade app version to 0.2.1

feat: upgrade app version to 0.2.1

---

Chart.yaml

Changes:
- upgrade app version to 0.2.2

feat: upgrade app version to 0.2.2

---

Chart.yaml
README.md
templates/deployment.yaml
values.yaml

Changes:
- Add shared host namespace hostIPC, hostPID and hostNetwork

Feat: add shared host namespace

---

Chart.yaml

- upgrade app version to 0.2.5
**Checklist:**

feat: upgrade app version to 0.2.5

---

Chart.yaml

- upgrade app version to 0.2.7
**Checklist:**

feat: upgrade app version to 0.2.7

---

Chart.yaml

- upgrade app version to 0.2.8
**Checklist:**

feat: upgrade app version to 0.2.8

---

Chart.yaml

- upgrade app version to 0.3.0
**Checklist:**

feat: upgrade app version to 0.3.0

---

Chart.yaml

- upgrade app version to 0.3.1
**Checklist:**

feat: upgrade app version to 0.3.1

---

Chart.yaml

- upgrade app version to 0.3.2
**Checklist:**

feat: upgrade app version to 0.3.2

---

Chart.yaml
README.md

- upgrade app version to 0.3.3
**Checklist:**

feat: upgrade app version to 0.3.3

---

README.md
templates/deployment.yaml
templates/knative/service.yaml
values.yaml

- add `topologySpreadConstraints` key
**Checklist:**

Feat: add topology spread constraints

---

Chart.yaml

- upgrade app version to 0.3.4
**Checklist:**

feat: upgrade app version to 0.3.4

---

Chart.yaml

- upgrade app version to 0.3.6
**Checklist:**

feat: upgrade app version to 0.3.6

---

Chart.yaml

feat: upgrade app version to 0.3.8

---

Chart.yaml

- upgrade app version to 0.3.9
**Checklist:**

feat: upgrade app version to 0.3.9

---

Chart.yaml

- upgrade app version to `0.3.10`
**Checklist:**

feat: upgrade app version to 0.3.10

---

Chart.yaml
templates/deployment.yaml
templates/knative/service.yaml

- lifecycle postStart hook waits ollama service (while boucle)
**Checklist:**

chore: lifecycle postStart hook waits ollama service

---

Chart.yaml

- upgrade app version to 0.3.11
**Checklist:**

feat: upgrade app version to 0.3.11

---

Chart.yaml

- upgrade app version to 0.3.12
**Checklist:**

feat: upgrade app version to 0.3.12

---

README.md
templates/service.yaml
values.yaml

Add support for loadBalancerIP

---

Chart.yaml

- upgrade app version to 0.3.13
**Checklist:**

feat: upgrade app version to 0.3.13

---

Chart.yaml

- upgrade app version to 0.3.14
**Checklist:**

feat: upgrade app version to 0.3.14

---

Chart.yaml
templates/deployment.yaml
templates/knative/service.yaml

Add missing implementation for subPath

---

Chart.yaml

- upgrade app version to 0.4.0
**Checklist:**

feat: upgrade app version to 0.4.0

---

Chart.yaml

Update appVersion in Chart.yaml to 0.4.1
**Checklist:**
* [ x ] I updated the `artifacthub.io/changes` annotation in _Chart.yml_ according to the [documentation](https://artifacthub.io/docs/topics/annotations/helm/#supported-annotations)

feat: Update appVersion to 0.4.1

---

Chart.yaml

- upgrade app version to 0.4.2
**Checklist:**

feat: upgrade appversion to 0.4.2

---

Chart.yaml

- upgrade app version to 0.4.3
**Checklist:**

feat: upgrade app version to 0.4.3

---

Chart.yaml

- upgrade app version to 0.4.4
**Checklist:**

feat: upgrade app version to 0.4.4

---

Chart.yaml

- upgrade app version to 0.4.7
**Checklist:**

feat: upgrade app version to 0.4.7

---

Chart.yaml

- upgrade app version to 0.5.1
**Checklist:**

feat: update app version to 0.5.1

---

Chart.yaml

- upgrade app version to 0.5.3
**Checklist:**

feat: upgrade app version to 0.5.3

---

Chart.yaml

- upgrade app version to 0.5.4
**Checklist:**

feat: upgrade app version to 0.5.4

---

Chart.yaml

- upgrade app version to 0.5.5
**Checklist:**

feat: upgrade app version to 0.5.5

---

Chart.yaml

- upgrade app verstion to 0.5.6
**Checklist:**

feat: upgrade app version to 0.5.6

---

Chart.yaml

-upgrade app version to 0.5.7
**Checklist:**

feat: upgrade app version to 0.5.7

---

Chart.yaml

- upgrade app version to 0.5.9
**Checklist:**

feat: upgrade app version to 0.5.9

---

Chart.yaml

- upgrade app version to 0.5.11
**Checklist:**

feat: upgrade app version to 0.5.11

---

.github/workflows/cd.yaml

feat: add CD

---

Chart.yaml

- upgrade app version to 0.5.12
**Checklist:**

feat: upgrade app version to 0.5.12

---

README.md

add --create-namespace flag in README.md

---

Chart.yaml

- upgrade app version to 0.6.0
**Checklist:**

feat: upgrade app version to 0.6.0

---

Chart.yaml

- upgrade app version to 0.6.1
**Checklist:**

feat: upgrade app version to 0.6.1

---

Chart.yaml

- upgrade app version to 0.6.2
**Checklist:**

feat: upgrade app version to 0.6.2

---

Chart.yaml

- upgrade app version to 0.6.3
**Checklist:**

feat: upgrade app version to 0.6.3

---

Chart.yaml

- upgrade app version to 0.6.4
**Checklist:**

feat: upgrade app version to 0.6.4

---

Chart.yaml

- upgrade app version to 0.6.5
**Checklist:**

feat: upgrade app version to 0.6.5

---

Chart.yaml

- upgrade app version to 0.6.8
**Checklist:**

feat: upgrade app version to 0.6.8

---

values.yaml

docs(values): typo in port section

---

Chart.yaml

- upgrade app version to 0.9.0
**Checklist:**

feat: upgrade app version to 0.9.0

---

Chart.yaml

- upgrade app version to 0.9.3
**Checklist:**

feat: upgrade app version to 0.9.3

---

Chart.yaml

- upgrade app version to 0.9.6
**Checklist:**

feat: upgrade app version to 0.9.6

---

Chart.yaml

- upgrade app version to 0.11.4
**Checklist:**

feat: upgrade app version to 0.11.4

---

Chart.yaml

- upgrade app version to 0.11.11
**Checklist:**

feat: upgrade app version to 0.11.11
